name: GunSmith
version: ${version}
main: com.gunsmith.GunSmithPlugin
api-version: '1.21'
folia-supported: false
authors: [ "AsadaReito", "ChatGPT" ]
description: GunSmith: firearms/ballistics (Paper 1.21.4)
permissions:
  gunsmith.use: { default: true }
commands:
  gm:
    description: GunSmith admin/user command
    usage: /gm <list|reload|give>
    permission: gunsmith.use
    aliases: [gunsmith]
