name: GunSmith
version: ${version}
main: com.gunsmith.GunSmithPlugin
api-version: '1.21'
folia-supported: false
authors: [ "AsadaReito", "ChatGPT" ]
website: https://example.com
description: "GunSmith: firearms/ballistics (Paper 1.21.4)"

permissions:
  gunsmith.use:
    default: true
  gunsmith.attach.*:
    default: op

