name: GunSmith
main: com.gunsmith.GunSmithPlugin
version: 0.1.0
api-version: '1.21'
author: AsadaReito
commands:
  gm:
    description: GunSmith main command
    usage: "/gm list | /gm give <weaponId> [player] | /gm reload | /gm help"
    aliases: [gunsmith]
permissions:
  gunsmith.use:
    default: true
