name: build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Generate Gradle Wrapper (8.10.2)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $ver = "8.10.2"
          Invoke-WebRequest "https://services.gradle.org/distributions/gradle-$ver-bin.zip" -OutFile gradle.zip
          Expand-Archive -Path gradle.zip -DestinationPath .
          $gradleExe = Join-Path -Path (Join-Path -Path $PWD -ChildPath "gradle-$ver") -ChildPath "bin\gradle.bat"
          if (-not (Test-Path $gradleExe)) { throw "Gradle exe not found at $gradleExe" }
          & "$gradleExe" wrapper --gradle-version $ver

      - name: Build with Wrapper
        shell: pwsh
        run: .\gradlew.bat build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GunSmith-jar
          path: build\libs\*.jar
